# Generated by Django 5.2.5 on 2025-10-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarDocumentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título do documento')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('capa', models.FileField(upload_to='capas/')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
