# Generated by Django 5.2.5 on 2026-06-09 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0005_animaismodels_necropsia_animaismodels_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('motivo', models.CharField(choices=[('tratamento', 'Apenas Tratamento Médico'), ('obito', 'Óbito'), ('transferencia', 'Transferência'), ('fuga', 'Fuga')], default='tratamento', max_length=20, verbose_name='Tipo de Ocorrência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Tratamento Clínico / Observações')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='animais.animaismodels')),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinicaDocumentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='fichas_clinicas/documentos/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ficha_clinica.fichaclinicamodel')),
            ],
        ),
    ]
