# Generated by Django 5.2.5 on 2026-06-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0008_animaismodels_identificacao'),
        ('ficha_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTratamentoTanqueModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Tratamento')),
            ],
            options={
                'verbose_name': 'Tipo de Tratamento',
                'verbose_name_plural': 'Tipos de Tratamento',
            },
        ),
        migrations.CreateModel(
            name='TratamentoTanqueModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição / Procedimento')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('data_tratamento', models.DateField(verbose_name='Data do Tratamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='animais.tanquemodels')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'ordering': ['-data_tratamento', '-data_criacao'],
            },
        ),
    ]
