# Generated by Django 5.2.5 on 2026-06-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_clinica', '0002_tipotratamentotanquemodels_tratamentotanquemodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamentotanquemodels',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ficha_clinica.tipotratamentotanquemodels', verbose_name='Tipo de Tratamento'),
            preserve_default=False,
        ),
    ]
