# Generated by Django 5.2.5 on 2026-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_clinica', '0003_tratamentotanquemodels_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamentotanquemodels',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberto'), ('fechada', 'Fechado')], default='aberta', max_length=20, verbose_name='Status'),
        ),
    ]
