# Generated by Django 5.2.5 on 2025-10-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TanqueModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('tipo', models.CharField(choices=[('DOCE', 'Água Doce'), ('SALGADA', 'Água Salgada'), ('SALOBRA', 'Água Salobra'), ('TERRESTRE', 'Terrestre'), ('AMBOS', 'Aquático & Terrestre')], max_length=10)),
                ('volume_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperatura_min', models.DecimalField(decimal_places=2, help_text='Temperatura mínima em °C', max_digits=5)),
                ('temperatura_max', models.DecimalField(decimal_places=2, help_text='Temperatura máxima em °C', max_digits=5)),
                ('ph_min', models.DecimalField(decimal_places=2, help_text='pH mínimo', max_digits=4)),
                ('ph_max', models.DecimalField(decimal_places=2, help_text='pH máximo', max_digits=4)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimaisModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comum', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(max_length=150)),
                ('habitat_natural', models.CharField(blank=True, max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=20, null=True)),
                ('alimentacao', models.CharField(blank=True, max_length=250, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('obito', models.BooleanField()),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.tanquemodels')),
            ],
        ),
    ]
