# Generated by Django 5.2.5 on 2025-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaismodels',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/'),
        ),
        migrations.AlterField(
            model_name='animaismodels',
            name='obito',
            field=models.BooleanField(default=False),
        ),
    ]
