# Generated by Django 5.2.5 on 2025-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animaismodels_foto_alter_animaismodels_obito'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaismodels',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO'), ('OUTROS', 'OUTROS')], default='', max_length=30, verbose_name='Sexo'),
        ),
    ]
