# Generated by Django 5.2.5 on 2026-03-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animaismodels_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaismodels',
            name='nome_cientifico',
        ),
        migrations.RemoveField(
            model_name='animaismodels',
            name='tipo_sanguineo',
        ),
    ]
