# Generated by Django 5.2.5 on 2026-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_remove_animaismodels_nome_cientifico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaismodels',
            name='necropsia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animaismodels',
            name='tratamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
