# Generated by Django 5.2.5 on 2026-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_animaismodels_necropsia_animaismodels_tratamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaismodels',
            old_name='nome_comum',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='animaismodels',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='animaismodels',
            name='habitat_natural',
        ),
        migrations.RemoveField(
            model_name='animaismodels',
            name='necropsia',
        ),
        migrations.RemoveField(
            model_name='animaismodels',
            name='tratamento',
        ),
        migrations.AddField(
            model_name='animaismodels',
            name='data_de_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='animaismodels',
            name='data_entrada',
            field=models.DateField(default='2026-02-03', verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animaismodels',
            name='mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animaismodels',
            name='pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
