# Generated by Django 5.2.5 on 2026-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_rename_nome_comum_animaismodels_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificacaoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_identificacao', models.CharField(max_length=100)),
            ],
        ),
    ]
