# Generated by Django 5.2.5 on 2026-06-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_identificacaomodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaismodels',
            name='identificacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animais.identificacaomodels'),
            preserve_default=False,
        ),
    ]
